import { Product, StoreInfo } from './types';

export const initialStoreInfo: StoreInfo = {
  name: "Mayur Sports",
  tagline: "Your Premier Destination for Authentic Sporting Goods & Equipment",
  phone: "+91 98220 12345",
  whatsapp: "919822012345",
  address: "Shop No 4, Navketan Building, M D, S Marg, below Hotel Vaishali, opp. CANARA BANK - MUMBAI CHEMBUR MAIN, Chembur",
  city: "Mumbai",
  state: "Maharashtra",
  pincode: "400071",
  openingHours: "Mon - Sat: 9:30 AM to 9:30 PM | Sun: 10:00 AM to 6:00 PM",
  announcement: "🔥 Special Tournament Season Discount: Up to 25% OFF on Cricket & Badminton Gear! Visit our Chembur shop or order directly on WhatsApp.",
};

export const initialProducts: Product[] = [
  {
    id: "prod-1",
    name: "SS Master 5000 English Willow Cricket Bat",
    category: "Cricket",
    brand: "SS Sunridges",
    price: 6499,
    mrp: 8999,
    stockStatus: "IN_STOCK",
    stockCount: 8,
    badge: "Best Seller",
    featured: true,
    description: "Handcrafted from premium grade 2 English Willow. Massive edges and contoured blade for tremendous power and balance. Comes with grain face protective sheet and padded bat cover.",
    features: [
      "Grade 2 Hand Selected English Willow",
      "Massive 40mm thick edges",
      "Short handle with 9-piece cane handle",
      "Lightweight pickup (1170 - 1200g)",
      "Pre-knocked with toe guard"
    ],
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-2",
    name: "Yonex Astrox 99 Play Graphite Badminton Racket",
    category: "Badminton",
    brand: "Yonex",
    price: 2690,
    mrp: 3490,
    stockStatus: "IN_STOCK",
    stockCount: 15,
    badge: "Popular",
    featured: true,
    description: "Designed for attacking and aggressive gameplay. Features the Rotational Generator System and slim shaft for swift counter-attacks and explosive smash power.",
    features: [
      "Head-Heavy balance for steep smashes",
      "High Modulus Full Graphite frame & shaft",
      "Weight: 4U (approx. 83g)",
      "String Tension: Up to 28 lbs",
      "Includes full Yonex thermal cover"
    ],
    imageUrl: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-3",
    name: "Nivia Storm Football - Size 5 (FIFA Basic)",
    category: "Football",
    brand: "Nivia",
    price: 899,
    mrp: 1250,
    stockStatus: "IN_STOCK",
    stockCount: 22,
    badge: "Hot Deal",
    featured: true,
    description: "Top choice for club level match play and hard turf training. 32-panel thermal bonded rubber construction offers high abrasion resistance and consistent bounce.",
    features: [
      "Rubberized molded outer layer",
      "High air retention butyl bladder",
      "All-weather playability (rain & turf)",
      "Official Size 5"
    ],
    imageUrl: "https://images.unsplash.com/photo-1579952363873-27f3bde9be2e?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-4",
    name: "SG Club Leather Cricket Ball (Pack of 2)",
    category: "Cricket",
    brand: "SG",
    price: 990,
    mrp: 1300,
    stockStatus: "IN_STOCK",
    stockCount: 30,
    badge: "Match Grade",
    featured: false,
    description: "Four-piece leather ball made from top quality alum tanned leather. Ideal for tournament and club match play with durable seam and long-lasting shine.",
    features: [
      "Waterproof alum tanned leather",
      "Solid cork interior core",
      "Prominent stitched seam for swing",
      "Standard red color match regulation"
    ],
    imageUrl: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-5",
    name: "Yonex Mavis 350 Nylon Shuttlecocks (Tube of 6)",
    category: "Badminton",
    brand: "Yonex",
    price: 1049,
    mrp: 1290,
    stockStatus: "IN_STOCK",
    stockCount: 45,
    badge: "Essential",
    featured: true,
    description: "The gold standard in nylon shuttlecock precision. Delivers close flight performance to natural feather shuttles with 4-5 times higher durability.",
    features: [
      "Wing Rib nylon lattice design",
      "Natural Portuguese cork base",
      "Yellow skirt for maximum visibility",
      "Medium speed (ideal for Indian temperatures)"
    ],
    imageUrl: "https://images.unsplash.com/photo-1613918108466-292b78a8ef95?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-6",
    name: "Kore PVC Hexagonal Dumbbells Set (10 KG - 5kg x 2)",
    category: "Fitness & Gym",
    brand: "Kore",
    price: 1199,
    mrp: 1899,
    stockStatus: "IN_STOCK",
    stockCount: 12,
    badge: "Gym Pick",
    featured: false,
    description: "Heavy duty anti-roll hexagonal dumbbells coated with tough PVC. Perfect for home workouts, bicep curls, chest press, and functional strength training.",
    features: [
      "Anti-roll hexagonal shape",
      "Floor-safe PVC rubber casing",
      "Ergonomic knurled grip",
      "Pair of 5kg each (10kg total)"
    ],
    imageUrl: "https://images.unsplash.com/photo-1586401100295-7a8096fd231a?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-7",
    name: "Nivia Ashtang Rubber Match Basketball - Size 7",
    category: "Accessories",
    brand: "Nivia",
    price: 849,
    mrp: 1150,
    stockStatus: "LOW_STOCK",
    stockCount: 4,
    badge: "Low Stock",
    featured: false,
    description: "Deep pebble channel design offers exceptional finger grip and control. Suitable for both concrete outdoor courts and indoor wooden parquet surfaces.",
    features: [
      "8-panel rubber composite shell",
      "Deep grip channels",
      "High bounce retention",
      "Standard Men's Size 7"
    ],
    imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-8",
    name: "Stag 2-Star Table Tennis Racket with Case",
    category: "Tennis & TT",
    brand: "Stag",
    price: 699,
    mrp: 950,
    stockStatus: "IN_STOCK",
    stockCount: 18,
    badge: "TT Special",
    featured: false,
    description: "ITTF approved rubber with 1.8mm sponge. Provides excellent spin and control for intermediate table tennis players and school competitions.",
    features: [
      "5-ply pure wood blade",
      "ITTF approved rubber",
      "Speed: 75 | Spin: 70 | Control: 85",
      "Free zip carry cover included"
    ],
    imageUrl: "https://images.unsplash.com/photo-1534158914592-062992fbe900?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-9",
    name: "Cosco Super Volley Volleyball",
    category: "Accessories",
    brand: "Cosco",
    price: 749,
    mrp: 999,
    stockStatus: "IN_STOCK",
    stockCount: 14,
    badge: "",
    featured: false,
    description: "18-panel laminated composite leather ball. Soft touch surface reduces sting on arms during hard spikes and serves.",
    features: [
      "Soft polyurethane composite cover",
      "18-panel precision glued seams",
      "Official weight and circumference",
      "Suitable for sand and hard indoor courts"
    ],
    imageUrl: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-10",
    name: "DSC Krunch 3.0 Cricket Batting Gloves",
    category: "Cricket",
    brand: "DSC",
    price: 1450,
    mrp: 1999,
    stockStatus: "IN_STOCK",
    stockCount: 10,
    badge: "Pro Protection",
    featured: true,
    description: "Split-finger design with multi-flex points for optimum flexibility and grip. Reinforced fiber inserts on lead fingers provide elite impact protection against fast bowling.",
    features: [
      "Premium sheep leather palm for soft feel",
      "High density foam with polymer fiber inserts",
      "Airflow mesh gusset for ventilation",
      "Elasticated double-sided sweatband wrist"
    ],
    imageUrl: "https://images.unsplash.com/photo-1593341646782-e0b495cff86d?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-11",
    name: "Nivia Premier Carbonite Sports & Running Shoes",
    category: "Shoes & Wear",
    brand: "Nivia",
    price: 1599,
    mrp: 2299,
    stockStatus: "IN_STOCK",
    stockCount: 16,
    badge: "Top Value",
    featured: false,
    description: "Ultra-breathable sports sneakers with responsive EVA cushioning. Ideal for gym training, running, badminton court practice, and daily athletic wear.",
    features: [
      "Breathable engineered mesh upper",
      "High-grip non-marking rubber outsole",
      "Cushioned die-cut EVA sockliner",
      "Available sizes: UK 6 to UK 11"
    ],
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-12",
    name: "Strauss Anti-Skid Yoga & Exercise Mat (6mm)",
    category: "Fitness & Gym",
    brand: "Strauss",
    price: 799,
    mrp: 1299,
    stockStatus: "OUT_OF_STOCK",
    stockCount: 0,
    badge: "Out of Stock",
    featured: false,
    description: "High density eco-friendly EVA foam with double-sided ribbed texture. Provides joint cushioning for yoga, pilates, stretching, and floor calisthenics.",
    features: [
      "6mm high-cushion thickness",
      "Sweat-resistant and easily washable",
      "Textured anti-slip pattern on both sides",
      "Free carry strap included"
    ],
    imageUrl: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
